<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

In [1]:
import numpy as np

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [16]:
nums = [1,2,3,4,5,6,7,8,9]
array1D = np.array(nums)
array1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [15]:
nums = [1,2,3,4,5,6,7,8,9,10]
array1DR = np.array(nums)
reforma = np.reshape(array1DR,(2,5))
reforma

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [30]:
cuqui = [0,2,0,4,0,4,0]
arr1D3 = np.array(cuqui)
indices = np.where(arr1D3 != 0)
print(f"Los índices donde no hay 0 son {indices}")

Los índices donde no hay 0 son (array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [29]:
np.random.randint(0,2,(3,3)) #El 2 no se incluye

array([[1, 0, 1],
       [1, 0, 0],
       [1, 1, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [40]:
array = np.random.randint(0,30,10)
array
array.max() #El máximo de todo el array

np.int32(29)

#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [95]:
ar1d = np.random.randint(1,20,10)
print(ar1d)
invertir = ar1d[::-1] #Con esto invertimos al revés
invertir

[19  9  5  5  8 19 19  9 11  5]


array([ 5, 11,  9, 19, 19,  8,  5,  5,  9, 19], dtype=int32)


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [83]:
arr3d = np.random.randint(1,25,(2,3,4))
print(arr3d)
print("Next")
sel1 = np.argmax(arr3d == 15) #Solo busca el primer valor que coincida
sel2 = arr3d[0,:,:] #Seleccionar todos los elementos del primer array
sel3 = arr3d[1,2,:]
print(sel1)
print("Next")
print(sel2)
print("Next")
print(sel3)

[[[ 8 11  6 20]
  [ 1 12 11 16]
  [ 5 22 11  6]]

 [[23  7 15 18]
  [19 11 18 11]
  [ 5 21  5 17]]]
Next
14
Next
[[ 8 11  6 20]
 [ 1 12 11 16]
 [ 5 22 11  6]]
Next
[ 5 21  5 17]


np.int64(14)


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [94]:
arr3d2 = np.random.randint(1,31,(3,2,5))
print(arr3d2)
sele1 = arr3d2[0,:,:2]
print(f"\nseleccion 1:\n{sele1}\n")
sele2 = arr3d2[1:3,:,:]
print("Seleccion 2\n")
print(sele2)

[[[14 12 20 11 25]
  [12 19 12  5 27]]

 [[16 16 17  5  9]
  [29  3  3  5 19]]

 [[18  8  6  6  1]
  [15 12  5 10 19]]]

seleccion 1:
[[14 12]
 [12 19]]

Seleccion 2

[[[16 16 17  5  9]
  [29  3  3  5 19]]

 [[18  8  6  6  1]
  [15 12  5 10 19]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [106]:
arr3d3 = np.random.randint(1,25,(4,3,2))
print(arr3d3)
print("")
print("Next")
arr3d3[1,1,:] = 0 #Esta es la manera de reemplazar los valores
print(arr3d3)
print("")
print("Next")
arr3d3[2,:,:] = -1 #Esta es la manera de reemplazar los valores
print(arr3d3)
print("")
print("Next")

[[[ 1 21]
  [ 7 12]
  [ 2 18]]

 [[10 15]
  [ 7 24]
  [22  4]]

 [[11  2]
  [ 5  8]
  [ 6 23]]

 [[20 12]
  [16  9]
  [ 3 18]]]

Next
[[[ 1 21]
  [ 7 12]
  [ 2 18]]

 [[10 15]
  [ 0  0]
  [22  4]]

 [[11  2]
  [ 5  8]
  [ 6 23]]

 [[20 12]
  [16  9]
  [ 3 18]]]

Next
[[[ 1 21]
  [ 7 12]
  [ 2 18]]

 [[10 15]
  [ 0  0]
  [22  4]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]

 [[20 12]
  [16  9]
  [ 3 18]]]

Next



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [114]:
arr3d4 = np.random.randint(-10,14,(2,4,3))
print(arr3d4)
busca = np.where(arr3d4 > 5) #Nos devuelve los índices 
encuentra = arr3d4[busca] #Nos devuelve los valores usando los índices ya buscados
print(encuentra)
reemplaza = np.where(arr3d4 < 0) #Usando la misma logica que la anterior
print("\nReemplazados\n")
arr3d4[reemplaza] = 0 #pero ahora le asigno valor 0 
arr3d4

[[[ -2  -3  -9]
  [ -1   9  10]
  [-10   4  -7]
  [  4  11   7]]

 [[  4   3  10]
  [  8  -2   6]
  [ -9  -6  13]
  [  8   8  -1]]]
[ 9 10 11  7 10  8  6 13  8  8]

Reemplazados



array([[[ 0,  0,  0],
        [ 0,  9, 10],
        [ 0,  4,  0],
        [ 4, 11,  7]],

       [[ 4,  3, 10],
        [ 8,  0,  6],
        [ 0,  0, 13],
        [ 8,  8,  0]]], dtype=int32)

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [126]:
arr3d5 = np.random.randint(1,28,(3,3,3))
print(f"\n{arr3d5}\nNext")
selec1 = arr3d5[1,:,:2]
print(f"\n{selec1}\nNext\n")
busc = np.where(arr3d5[2,:,:] > 20) #Buscas en la tercera directamente
selec2 = arr3d5[2,:,:][busc] #tenemos que volver a currar
print(selec2)


[[[24 16  3]
  [ 2  4 15]
  [23  5 15]]

 [[22 26 19]
  [18  2 22]
  [23 12 16]]

 [[12 10 11]
  [23 12  6]
  [20 12 25]]]
Next

[[22 26]
 [18  2]
 [23 12]]
Next



IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [135]:
arr = np.random.randint(1,30,10)
print(arr)
print("")
maximo = np.max(arr)
minimo = np.min(arr)
busca_max = np.where(arr == maximo)
busca_min = np.where(arr == minimo)
arr[busca_max] = 0
arr[busca_min] = 0
print(arr)
print("")

[21 20 14 20  3 27 18 23 16 10]

[21 20 14 20  0  0 18 23 16 10]



#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [137]:
arr2 = np.random.randint(1,101,15)
arr2.sort() #ordernar de forma ascendente
print(arr2)

[13 15 30 34 35 37 40 47 63 69 70 79 95 96 96]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [141]:
matr = np.random.randint(0,40,(1,4,4))
print(matr)
np.sum(matr)

[[[12  2 31 28]
  [19  5 13 19]
  [ 2 27  7 35]
  [32 21 23 29]]]


np.int64(305)

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [148]:
matr2 = np.zeros((5,5), dtype= int)
matr2[0,:] = 1 #Arriba
matr2[4,:] = 1 #Abajo
matr2[:,0] = 1 #izquierda
matr2[:,4] = 1 #derecha
matr2

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [154]:
arr3 = np.random.randint(1,50,10)
print(f"{arr3}\n")
media = np.mean(arr3)
print(f" La media es: {media}")
desv_std = np.std(arr3)
print(f"La desviación es de: {desv_std}")

[13 27 24 32 11  1 21 33 21 45]

 La media es: 22.8
La desviación es de: 11.906300852909773


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


# Respuesta
Lo que ha ocurrido es que la función se ha transpuesto 
Le hemos indicado que de 2 matrices de 3 filas y 4 columnas,
la transponga a 4 matrices, 3 filas y 2 columnas 
en transpose se usan indices en vez de los números de forma que lo coge donde creamos la matriz 
es decir para:
```python
    #                               Indices
    #declarar función                0 1 2
    matr3d = np.random.randint(1,25,(2,3,4))
    #                               Valores
```
El transpose a 4,3,2 será:
```python
    #                                Valores
    #declarar función                 4,3,2
    transponer = np.transpose(matr3d,(2,1,0)) 
    #                                Indices
```
El resultado es que ahora tenemos cada columna de ambas matrices en una matriz por columna, es decir

    --                                           --
    | Matriz1Columna1Fila1 | Matriz2Columna1Fila1 |
    | Matriz1Columna1Fila2 | Matriz2Columna1Fila2 |
    --                                           --

In [158]:
matr3d = np.random.randint(1,25,(2,3,4))
print(f"{matr3d}\n")
#Recuerda que los numeros aqui son los índices de 0 a 2 de cuando creas la matriz y le dices tamaño
transponer = np.transpose(matr3d,(2,1,0)) 
print(f"Transponer:\n{transponer}\n")


[[[12 16  7 12]
  [13  7 16  3]
  [ 6  4 18 15]]

 [[13  5  4  4]
  [18  1 17 19]
  [15 11 11  9]]]

Transponer:
[[[12 13]
  [13 18]
  [ 6 15]]

 [[16  5]
  [ 7  1]
  [ 4 11]]

 [[ 7  4]
  [16 17]
  [18 11]]

 [[12  4]
  [ 3 19]
  [15  9]]]



#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [160]:
r2d2 = np.random.randint(1,25,(3,4,2))
print(f"{r2d2}\n")
transponer2 = np.transpose(r2d2,(2,1,0)) 
print(transponer2)

[[[21 12]
  [23  7]
  [ 3  8]
  [14 20]]

 [[11  2]
  [ 6  1]
  [14 24]
  [20 16]]

 [[21  4]
  [14 22]
  [ 8  1]
  [ 5 11]]]

[[[21 11 21]
  [23  6 14]
  [ 3 14  8]
  [14 20  5]]

 [[12  2  4]
  [ 7  1 22]
  [ 8 24  1]
  [20 16 11]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [166]:
r2d2 = np.random.randint(1,25,(3,2,4))
print(f"{r2d2}\n")
swapeje = np.swapaxes(r2d2,2,1)
print(f"Swap Ejes\n{swapeje}")

[[[17  8 23  7]
  [ 5  6 24  1]]

 [[ 5 18  3  3]
  [ 7 11 24  1]]

 [[18 22 18 24]
  [24  9 16  9]]]

Swap Ejes
[[[17  5]
  [ 8  6]
  [23 24]
  [ 7  1]]

 [[ 5  7]
  [18 11]
  [ 3 24]
  [ 3  1]]

 [[18 24]
  [22  9]
  [18 16]
  [24  9]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [212]:
triforce = np.random.randint(-10,11,(3,4,5))
print(triforce)
vacio = np.empty((3,4,5),dtype='<U100') #usamos esto para tener más de una letra en los arrays, si solo es una ponemos str 
mediana = np.median(triforce)
buscar_mediana = np.where(triforce == mediana)
maximos = np.max(triforce)
minimos = np.min(triforce)
busca_max = np.where(triforce == maximos)
busca_min = np.where(triforce == minimos)
mayorm = np.where((triforce > mediana) & (triforce < maximos))
menorm = np.where((triforce < mediana)&(triforce > minimos))

vacio[buscar_mediana] = "M"
vacio[busca_max] = "MAX" 
vacio[busca_min] = "MIN"
vacio[mayorm] = "X"
vacio[menorm] = "Y"
print(busca_max)
print(maximos)
print(minimos)
print()
print(mediana)
print()
print(vacio)

[[[  7   7   3   2   6]
  [  3  -5   1   2   1]
  [  0   7 -10   5  10]
  [ -6   7   4  -5  -7]]

 [[  7   5  -5   9   2]
  [  3   3   4   5  -3]
  [  3   5   3  -9   5]
  [  7  10  -3  -5  -4]]

 [[  3  -3  -1   8  -1]
  [ -4   1  -9   9   0]
  [-10  -5   6   1  -7]
  [  1 -10   9  10  -2]]]
(array([0, 1, 2]), array([2, 3, 3]), array([4, 1, 3]))
10
-10

2.0

[[['X' 'X' 'X' 'M' 'X']
  ['X' 'Y' 'Y' 'M' 'Y']
  ['Y' 'X' 'MIN' 'X' 'MAX']
  ['Y' 'X' 'X' 'Y' 'Y']]

 [['X' 'X' 'Y' 'X' 'M']
  ['X' 'X' 'X' 'X' 'Y']
  ['X' 'X' 'X' 'Y' 'X']
  ['X' 'MAX' 'Y' 'Y' 'Y']]

 [['X' 'Y' 'Y' 'X' 'Y']
  ['Y' 'Y' 'Y' 'X' 'Y']
  ['MIN' 'Y' 'X' 'Y' 'Y']
  ['Y' 'MIN' 'X' 'MAX' 'Y']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [95]:
bifrutas = np.random.randint(1,20,(4,4))
print(f"{bifrutas}\n")
filas = [0,1,2,3]
columnas = [0,1,2,3]

for c in range (0,4):
    for f in range(0,4):
        x = bifrutas[f,:] == bifrutas[:,c]
        contar = 0
        for i in range(0,len(x)):
            if x[i] == np.True_:
                contar += 1
                i += 1
            else:
                i+=1

        if contar < 4:
            f += 1
        elif contar == 4:
            print(f"La fila {f} es igual que la columna {c}")
    c+= 1
   


[[ 3  4 17  2]
 [ 1  4 14  8]
 [17  4 16 15]
 [ 7  9  2 19]]

